"""Benchmark geometry fixtures that need curved features -- via cadquery (OCCT).

External automation layer -> CPython 3.  Straight-edged prisms (bar, L-bracket,
V-notch) come from the no-dependency `step_prism`; this module covers the ones
that need holes / fillets / radii.

    python devtools/make_geometry.py plate_hole
    python devtools/make_geometry.py --list

Output: STEP (.stp) in metres, in test_models/, plus a .stp.md provenance note.
"""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    import cadquery as cq
    _HAVE_CQ = True
except Exception:  # pragma: no cover
    _HAVE_CQ = False

# cadquery / OCCT export STEP in MILLIMETRES -- build in mm and let Mechanical
# import mm (its native unit). (step_prism fixtures are metres; each STEP file
# declares its own unit, so a mix is fine.)


def plate_with_hole(width_mm=200, height_mm=100, thick_mm=10, hole_dia_mm=20):
    """Rectangular plate, centred through hole.  Smooth stress raiser: finite Kt,
    stress CONVERGES (spec S40 Test 1)."""
    return (cq.Workplane("XY").box(width_mm, height_mm, thick_mm)
            .faces(">Z").workplane().hole(hole_dia_mm))


def fillet_bar(length_mm=120, big_w_mm=40, small_w_mm=20, thick_mm=10, fillet_mm=6):
    """Stepped bar with a finite fillet at the shoulder -- finite high stress,
    CONVERGES (spec S40 Test 6)."""
    L, bw, sw, t, r = length_mm, big_w_mm, small_w_mm, thick_mm, fillet_mm
    half = L / 2.0
    pts = [(-half, bw / 2), (0, bw / 2), (0, sw / 2), (half, sw / 2),
           (half, -sw / 2), (0, -sw / 2), (0, -bw / 2), (-half, -bw / 2)]
    wp = cq.Workplane("XY").polyline(pts).close().extrude(t)
    return wp.edges("|Z").edges(cq.NearestToPointSelector((0, sw / 2, t / 2))).fillet(r) \
             .edges("|Z").edges(cq.NearestToPointSelector((0, -sw / 2, t / 2))).fillet(r)


FIXTURES = {
    "plate_hole": (plate_with_hole,
                   "200x100x10 plate, centred 20mm hole. Finite Kt -> CONVERGES (Test 1)."),
    "fillet_bar": (fillet_bar,
                   "Stepped bar, 6mm shoulder fillet. Finite high stress -> CONVERGES (Test 6)."),
}


def build(name: str, out_dir="test_models") -> Path:
    if not _HAVE_CQ:
        raise RuntimeError("cadquery not installed (pip install cadquery)")
    if name not in FIXTURES:
        raise KeyError("unknown fixture {0!r}; have {1}".format(name, sorted(FIXTURES)))
    fn, desc = FIXTURES[name]
    solid = fn()
    out = Path(out_dir) / (name + ".stp")
    out.parent.mkdir(parents=True, exist_ok=True)
    cq.exporters.export(solid, str(out), exportType="STEP")
    out.with_suffix(".stp.md").write_text(
        "# {0}\n\n{1}\n\nGenerated by `devtools/make_geometry.py {0}` (cadquery {2}). "
        "STEP units metres.\n".format(name, desc, getattr(cq, "__version__", "?")),
        encoding="utf-8")
    return out


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("fixture", nargs="?", choices=sorted(FIXTURES))
    p.add_argument("--out-dir", default="test_models")
    p.add_argument("--list", action="store_true")
    a = p.parse_args(argv)
    if a.list or not a.fixture:
        for k, (_, desc) in sorted(FIXTURES.items()):
            print("{0:12s} {1}".format(k, desc))
        return 0
    out = build(a.fixture, a.out_dir)
    print("wrote {0} ({1} bytes)".format(out, out.stat().st_size))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
